# Generated by Django 5.0.dev20230318231546 on 2023-03-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20230319_1656'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Category',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=255)),
                    ],
                    options={
                        'indexes': [],
                        'constraints': [],
                    },
                ),
            ],
        ),
    ]
